spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        ssl:
          enabled: false


#server:
#    port: 8081
#spring.rabbitmq.publisher-confirm-type=correlated
#spring.rabbitmq.publisher-returns=true