spring:
    rabbitmq:
        host: ec2-3-120-159-96.eu-central-1.compute.amazonaws.com
        port: 8081
        username: guest
        password: guest
        ssl:
          enabled: false

#spring.rabbitmq.publisher-confirm-type=correlated
#spring.rabbitmq.publisher-returns=true